version: '3.8'

services:
  bdd-api-utilisateur:
    image: mariadb:latest
    container_name: BDD-API-UTILISATEUR
    restart: always
    volumes:
      - bdd_api_utilisateur_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mot-magique
      MYSQL_DATABASE: bdd-api-utilisateur
      MYSQL_USER: utilisateurBDD
      MYSQL_PASSWORD: mot-magique
    ports:
      - "3307:3306"

  quarkus-api-utilisateur:
    depends_on:
      - bdd-api-utilisateur
    image: alesque29/tes-api-rest-utilisateur:latest
    container_name: QUARKUS-API-UTILISATEUR
    restart: always
    ports:
      - "8081:8081"

  bdd-api-articlevendu:
    image: mariadb:latest
    container_name: BDD-API-ARTICLEVENDU
    restart: always
    volumes:
      - bdd_api_articlevendu_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mot-magique
      MYSQL_DATABASE: bdd-api-articlevendu
      MYSQL_USER: utilisateurBDD
      MYSQL_PASSWORD: mot-magique
    ports:
      - "3308:3306"

  quarkus-api-articlevendu:
    depends_on:
      - bdd-api-articlevendu
    image: alesque29/tes-api-rest-articlevendu:latest
    container_name: QUARKUS-API-ARTICLEVENDU
    restart: always
    ports:
      - "8082:8082"

  bdd-api-enchere:
    image: mariadb:latest
    container_name: BDD-API-ENCHERE
    restart: always
    volumes:
      - bdd_api_enchere_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mot-magique
      MYSQL_DATABASE: bdd-api-enchere
      MYSQL_USER: utilisateurBDD
      MYSQL_PASSWORD: mot-magique
    ports:
      - "3309:3306"

  quarkus-api-enchere:
    depends_on:
      - bdd-api-enchere
    image: alesque29/tes-api-rest-enchere:latest
    container_name: QUARKUS-API-ENCHERE
    restart: always
    ports:
      - "8083:8083"

  bdd-api-imagearticle:
    image: mariadb:latest
    container_name: BDD-API-IMAGEARTICLE
    restart: always
    volumes:
      - bdd_api_imagearticle_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mot-magique
      MYSQL_DATABASE: bdd-api-imagearticle
      MYSQL_USER: utilisateurBDD
      MYSQL_PASSWORD: mot-magique
    ports:
      - "3310:3306"

  quarkus-api-imagearticle:
    depends_on:
      - bdd-api-imagearticle
    image: alesque29/tes-api-rest-imagearticle:latest
    container_name: QUARKUS-API-IMAGEARTICLE
    restart: always
    ports:
      - "8084:8084"

  php-myadmin-tes:
    depends_on:
      - bdd-api-utilisateur
      - bdd-api-articlevendu
      - bdd-api-enchere
      - bdd-api-imagearticle
    image: phpmyadmin/phpmyadmin:latest
    container_name: PHP-MYADMIN-TES
    restart: always
    environment:
      PMA_HOSTS: bdd-api-utilisateur, bdd-api-articlevendu, bdd-api-enchere, bdd-api-imagearticle
      MYSQL_ROOT_PASSWORD: mot-magique
    ports:
      - 8181:80

volumes:
  bdd_api_utilisateur_data:
  bdd_api_articlevendu_data:
  bdd_api_enchere_data:
  bdd_api_imagearticle_data: